name: tests and publish docker container

on:
  push:
    tags:
      - '**'

jobs:
  all:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout repo and subrepos
        uses: actions/checkout@v2
      - 
        name: Publish to npmjs.com
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
